### PR TITLE
supertype in subtype

### LINKED ISSUE #126: sub type did not have super type as struct
Should be
```rust
enum PetAny {
  Pet(Box<Pet>),
  Cat(Box<Cat>),
  Rabbit(Box<Rabbit>),
  Dog(Box<Dog>)
}
struct Pet {
  name: String,
}
struct Cat {
  pet: Pet,
  // other field if exists
}
```

Current status
```rust
enum PetAny {
  Pet(Box<Pet>),
  Cat(Box<Cat>),
  Rabbit(Box<Rabbit>),
  Dog(Box<Dog>)
}
struct Pet {
  name: String,
}
struct Cat {
  // do not have pet
  // other field if exists
}
```

I pushed `any_in_struct` for add `pet: Pet` at `Cat`. However, this fix is a bit ad-hoc in the `is_supertype` fix, and the build of `ap201.rs` did not pass due to a problem with the derive macro in the deserializer.

### PR DESCRIPTION
**Pull request by ytanimura**
Close #126

### CODE REVIEW

**Comment by ytanimura** [comment]
Summary of changes
- Adds supertype into subtype as a field.
```rust
pub struct Cat {
    pub pet: Pet,
    pub tail_color: String,
}
```
- Adds table both of `SuperType` and `SuperTypeAny`.
```rust
pub struct Tables {
    pet: HashMap<u64, as_holder!(Pet)>,
    pet_any: HashMap<u64, as_holder!(PetAny)>,
    cat: HashMap<u64, as_holder!(Cat)>,
}
```

The secondary change perhaps superfluity...

Original EXPRESS for example:
```
SCHEMA pets;

ENTITY pet;
	name: STRING;
END_ENTITY;

ENTITY cat SUBTYPE OF (pet);
	tail_color: STRING;
END_ENTITY;

END_SCHEMA;
```

**Comment by termoshtt** [comment]
> Adds table both of SuperType and SuperTypeAny.

This should not be added. In original design, `impl EntityTable<XxxAny> for Tables { ... }` should be used to get owned `XxxAny` type from `Tables`.

This `impl` will be generated by [ruststep_derive::select::Input::impl_entity_table](https://github.com/ricosjp/ruststep/blob/master/ruststep-derive/src/select.rs#L235), but it seems `ruststep::ap201` lacks it (this must be a bug).

**Comment by termoshtt** [comment]
> This impl will be generated by ruststep_derive::select::Input::impl_entity_table, but it seems ruststep::ap201 lacks it (this must be a bug).

I will fix this in #135. For this PR,

> Adds table both of SuperType and SuperTypeAny.

please remove this part, and focus only on the first "Adds supertype into subtype as a field." part.

**Comment by ytanimura** [comment]
It has been modified to conform to the source code https://github.com/ricosjp/ruststep/blob/master/ruststep/tests/any_deserialize.rs .

**Comment by ytanimura** [comment]
Now, exprc is refactored #165. Rebuilt the pull request #166 again.

**Pull request closed without merging**
