### PR TITLE
Case sensitivity fix #54

### LINKED ISSUE #54: Case sensitivity in EXPRESS schema
As far as I read ISO-10303-11, user defined identifiers should be snake_case, but some identifier copied into `schema/` does contains non snake_case identifier like `degree_Celsius`

### PR DESCRIPTION
**Pull request by g-rauhoeft**
This pull request fixes case sensitivity for the Express Parser in accordance with ISO-10303-11, as discussed under https://github.com/ricosjp/ruststep/issues/54

This was achieved by restricting identifiers to anything but reserved keywords, which is defined in the standard. It also changes the order of operations for certain alt parsers, because some are implemented in a way that they take precedence over subsequent parsers if case sensitivity is ignored.

### CODE REVIEW

**Comment by g-rauhoeft** [comment]
Could you please let me know if this pull request is acceptable? A lot of fixes I'm working on depend on the changes I've made here and it would be a shame to put more effort in to something that won't be accepted.

**Comment by ytanimura** [comment]
We apologize for not responding to you earlier.
The main developer @termoshtt of ruststep is recently very busy, and cannot check the commits precisely now.
We will announce the deadline for determination as soon as possible, so please wait a little longer.

**Comment by termoshtt** [comment]
> Could you please let me know if this pull request is acceptable?

To merge this PR requires me re-reading and understanding the ISO-10303-11 with discussed in #54, and it takes more time for review. 

> A lot of fixes I'm working on depend on the changes I've made here and it would be a shame to put more effort in to something that won't be accepted.

This pull requrest has some independent parts e.g. `eof` or `not` parsers. If you need these parts in other branches, It can be merged independently when you split them into individual pull requests.

**Comment by g-rauhoeft** [comment]
Thank you for your reply. As for the part on case sensitivity, the definition is under ```7.1.2 Letters```. Throughout the document I have seen several examples of EXPRESS keywords being written in either upper or lower case. ```6.1 The syntax of the specification``` refers to keywords being in uppercase, but that is only for the syntax of the specification in WSN, not for EXPRESS as such.

I'll try and split my pull request in to smaller pieces, but the main aim of this PR was to get case-insensitivity working, which is quite a large operation on the code base. My subsequent edits with which I managed to parse serveral APs rely on case-insensitivity unfortunately.

**Pull request merged**
